Repository TeamPiickle/server, pull requests merged in 2022-07, with the labels that each got.

#19 [HOTFIX] ERROR HANDLER 수정
  src/middlewares/errorHandler.ts
Labels: hotfix

#21 [CHORE] 충돌 바로잡기
  src/middlewares/errorHandler.ts
  src/modules/responseMessage.ts
Labels: 동현💩, hotfix

#23 [HOTFIX] 로그인 로직 수정
  src/controllers/CategoryController.ts
  src/controllers/userController.ts
  src/routes/userRouter.ts
  src/services/userService.ts
Labels: 동현💩, hotfix

#24 [FEAT] 유저 프로필 조회 API
  src/controllers/userController.ts
  src/intefaces/common.ts
  src/intefaces/user/UserLoginDto.ts
  src/intefaces/user/UserProfileResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/userRouter.ts
  src/services/userService.ts
Labels: feature, 동현💩

#30 [FEAT] 유저 닉네임 변경 API
  src/controllers/userController.ts
  src/intefaces/common.ts
  src/middlewares/errorHandler.ts
  src/modules/responseMessage.ts
  src/routes/userRouter.ts
  src/services/userService.ts
Labels: feature, 동현💩

#36 [FEAT] 카테고리별 대화 주제 리스트 조회
  src/controllers/CategoryController.ts
  src/intefaces/CardResponseDto.ts
  src/intefaces/CategoryResponseDto.ts
  src/models/card.ts
  src/models/category.ts
  src/models/interface/ICard.ts
  src/modules/responseMessage.ts
  src/routes/CategoryRouter.ts
  src/services/CategoryService.ts
Labels: feature, 승빈🎃

#37 [FEAT] 프로필 사진 수정 API
  package.json
  src/config/index.ts
  src/config/multer.ts
  src/config/s3Config.ts
  src/controllers/userController.ts
  src/intefaces/common.ts
  src/intefaces/user/UserProfileImageUrlDto.ts
  src/intefaces/user/UserUpdateNicknameDto.ts
  src/middlewares/auth.ts
  src/modules/responseMessage.ts
  src/routes/userRouter.ts
  src/services/userService.ts
Labels: feature, 동현💩

#43 [FIX] Readme.md 수정
  README.md
Labels: 동현💩, hotfix, docs

#46 [FIX] 카드 스키마 수정
  src/models/bookmark.ts
  src/models/card.ts
  src/models/category.ts
  src/models/interface/IBookmark.ts
  src/models/interface/ICard.ts
  src/models/interface/ICategory.ts
  src/models/interface/IUser.ts
  src/models/user.ts
Labels: feature, 승빈🎃

#50 [FIX] 간편 대화주제 카테고리 리스트 조회
  src/controllers/index.ts
  src/services/CategoryService.ts
Labels: 승빈🎃, hotfix

#51 [FEAT] 대화주제 추천 리스트 조회
  src/controllers/CategoryController.ts
  src/modules/responseMessage.ts
  src/routes/CategoryRouter.ts
  src/services/CategoryService.ts
Labels: feature, 승빈🎃

#53 [FEAT] 북마크 조회 API 구현
  src/controllers/userController.ts
  src/intefaces/user/UserBookmarkDto.ts
  src/modules/responseMessage.ts
  src/routes/userRouter.ts
  src/services/userService.ts
Labels: feature, 동현💩

#74 [HOTFIX] 투표 현황 조회시 투표 제목 반환 추가
  src/services/ballotService.ts
Labels: hotfix

#86 [HOTFIX] 카드 북마크 여부 반환
  src/controllers/CategoryController.ts
  src/controllers/cardController.ts
  src/intefaces/CardResponseDto.ts
  src/routes/CategoryRouter.ts
  src/routes/cardRouter.ts
  src/services/CategoryService.ts
  src/services/cardService.ts
Labels: 동현💩, hotfix

#95 [HOTFIX] jwt 토큰 유효시간 수정
  src/modules/jwtHandler.ts
Labels: 동현💩, hotfix

#97 [HOTFIX] 마이피클 조회 필드값 수정
  src/intefaces/user/UserBookmarkDto.ts
  src/services/userService.ts
Labels: 동현💩, hotfix

#99 [HOTFIX] 투표 항목 조회 로직 수정
  src/services/ballotService.ts
Labels: 동현💩, hotfix

#105 [HOTFIX] 투표 현황 조회 필드값 수정
  src/services/ballotService.ts
Labels: 동현💩, hotfix

#108 [TEST] 테스트 코드 작성
  .husky/pre-commit
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/CategoryController.ts
  src/controllers/ballotController.ts
  src/controllers/cardController.ts
  src/index.ts
  src/middlewares/auth.ts
  src/middlewares/errorHandler.ts
  src/modules/returnToSlack.ts
  src/modules/slackApi.ts
  test/ballot.spec.ts
  test/card.spec.ts
  test/category.spec.ts
  test/user.spec.ts
  test/스크린샷 2022-07-04 오후 8.30.19.png
  tsconfig.json
Labels: 동현💩, test
