Repository TeamPiickle/server, pull requests merged in 2023-08, with the labels that each got.

#196 [HOTFIX] 소셜 회원가입 시 기존 회원의 가입 여부를 검증 로직 변경
  src/controllers/userController.ts
  src/intefaces/createUserCommand.ts
  src/models/user/user.ts
  src/services/socialAuthService.ts
  src/services/userService.ts
Labels: 동현💩, hotfix

#200 [HOTFIX] 카드 조회시 랜덤 조회로 수정
  src/services/cardService.ts
Labels: 동현💩, hotfix

#203 feat: 스키마 구성
  src/loaders/db.ts
  src/models/mind23/comment.ts
  src/models/mind23/prizeEntry.ts
  src/models/mind23/question.ts
Labels: feature

#204 [FEAT] Mind23 프로덕트 용 API
  src/controllers/index.ts
  src/controllers/mind23Controller.ts
  src/intefaces/mind23/CommentDto.ts
  src/intefaces/mind23/Mind23CardResponseDto.ts
  src/intefaces/mind23/QuestionDto.ts
  src/intefaces/mind23/QuestionResponseDto.ts
  src/models/mind23/comment.ts
  src/models/mind23/question.ts
  src/modules/responseMessage.ts
  src/routes/index.ts
  src/routes/mind23Router.ts
  src/services/index.ts
  src/services/mind23Service.ts
  src/services/userService.ts
Labels: feature, 동현💩

#210 [HOTFIX] 당일용 프로덕트 댓글 관련 API 수정
  src/controllers/mind23Controller.ts
  src/intefaces/mind23/CommentDto.ts
  src/models/mind23/prizeEntry.ts
  src/services/mind23Service.ts
Labels: 동현💩, hotfix

#212 [HOTFIX] 질문 조회 esstional 값 제거
  src/intefaces/mind23/Mind23CardResponseDto.ts
  src/services/mind23Service.ts
Labels: 동현💩, hotfix
