Repository TeamPiickle/server, pull requests merged in 2023-07, with the labels that each got.

#186 [FEAT] 블랙리스트 제외 카드 조회
  src/services/CategoryService.ts
  src/services/cardService.ts
Labels: feature, 동현💩

#191 [HOTFIX] 요청에서 성별을 선택으로 변경
  src/controllers/userController.ts
  src/intefaces/createUserCommand.ts
  src/models/user/gender.ts
Labels: bug

#194 [HOTFIX] 최근 북마크 된 카드 조회 시 중복 제거
  src/services/cardService.ts
Labels: 동현💩, hotfix
